language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
script: 
- xcodebuild -project YTVimeoExtractor.xcodeproj -scheme YTVimeoExtractor test -destination 'platform=OS X,arch=x86_64' -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=latest'
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - carthage build --no-skip-current
  - carthage archive YTVimeoExtractor
skip_cleanup: true
on:
  repo: repo/repo
  tags: true
